"""Report generator module for Trust WEDO."""

import json
from pathlib import Path
from typing import Dict, List, Any
from trust_wedo.utils.meta import get_meta


class ReportGenerator:
    """Generator for final trust reports (MD/JSON)."""

    def __init__(self, bundle_dir: str):
        self.bundle_path = Path(bundle_dir)
        self.data: Dict[str, Any] = {}
        self._load_bundle()

    def _load_bundle(self) -> None:
        """Load all JSON files from bundle."""
        files = {
            "site": "site.json",
            "entity": "entity_profile.json",
            "afb": "afb.json",
            "citation": "citation_eval.json",
            "graph": "entity_graph.json"
        }
        for key, filename in files.items():
            file_path = self.bundle_path / filename
            if file_path.exists():
                with open(file_path) as f:
                    self.data[key] = json.load(f)

    def generate_json(self) -> Dict[str, Any]:
        """Generate aggregated JSON report."""
        return {
            "meta": get_meta(str(self.bundle_path)),
            "summary": {
                "entity_id": self.data.get("entity", {}).get("entity_id"),
                "ec_score": self.data.get("entity", {}).get("entity_confidence"),
                "eligibility": self.data.get("entity", {}).get("eligibility"),
                "citation_decision": self.data.get("citation", {}).get("decision"),
                "risk_detected": self.data.get("graph", {}).get("metrics", {}).get("single_source_risk", False)
            },
            "details": self.data
        }

    def generate_markdown(self) -> str:
        """Generate Markdown report."""
        summary = self.data.get("entity", {})
        citation = self.data.get("citation", {})
        graph = self.data.get("graph", {}).get("metrics", {})
        
        md = f"""# Trust WEDO 信任評估報告

## 1. 實體概覽
- **實體 ID**: `{summary.get('entity_id', 'N/A')}`
- **信任評分 (EC)**: `{summary.get('entity_confidence', 0.0):.2f}`
- **判定結果**: `{"✅ 通過" if summary.get('eligibility') == 'pass' else "❌ 拒絕"}`

### 信任信號
| 信號 | 分數 |
|------|------|
| Consistency | {summary.get('signals', {}).get('consistency', 0.0)} |
| Authority | {summary.get('signals', {}).get('authority', 0.0)} |
| Citation | {summary.get('signals', {}).get('citation', 0.0)} |
| Frequency | {summary.get('signals', {}).get('frequency', 0.0)} |
| Social | {summary.get('signals', {}).get('social', 0.0)} |

## 2. 答案物件 (AFB)
- **AFB ID**: `{self.data.get('afb', {}).get('afb_id', 'N/A')}`
- **AI 快速答案**: {self.data.get('afb', {}).get('ai_quick_answer', 'N/A')}

## 3. 引用評估
- **最終決策**: `{citation.get('decision', 'N/A')}`
- **引用數量**: {len(citation.get('citations', []))}

## 4. 風險檢測
- **來源多樣性**: {graph.get('distinct_sources', 0)}
- **孤立實體**: `{"是" if graph.get('is_isolated') else "否"}`
- **單一來源風險**: `{"🔴 高" if graph.get('single_source_risk') else "🟢 低"}`

---
*Generated by Trust WEDO CLI v0.1.0*
"""
        return md
